function generateName() {
    const names = [
      "Advocate",
      "Almighty",
      "Almighty God",
      "Alpha and Omega",
      "Author and finisher of our faith",
      "Being",
      "Beloved",
      "Beloved Son",
      "Bishop of your Souls",
      "Branch",
      "Bread of Life",
      "Bright and morning star",
      "Captain",
      "Carpenter",
      "Chief Cornerstone",
      "Chosen of God",
      "Christ",
      "Christ Jesus",
      "Christ the Son",
      "Counselor (Counsellor)",
      "Creator",
      "Deliverer",
      "Emmanuel",
      "Eternal Father",
      "Eternal God",
      "Eternal Head",
      "Eternal Judge",
      "Everlasting Father",
      "Everlasting God",
      "Faithful WItness",
      "Father",
      "Father of heaven",
      "Father of heaven and of earth",
      "First Begotten",
      "Firstfruits of them that slept",
      "Forerunner",
      "Founder of Peace",
      "Fountain of living waters",
      "God",
      "God of Abraham",
      "God of Abraham, and Isaac, and Jacob",
      "God of Abraham, and of Isaac, and the God of Jacob",
      "God of Isaac",
      "God of Israel",
      "God of Jacob",
      "God of miracles",
      "God of nature",
      "God of the whole earth",
      "Good Shepherd",
      "Great Creator",
      "Great Spirit",
      "Head",
      "High Priest",
      "Holy Child",
      "Holy God",
      "Holy Messiah",
      "Holy One",
      "Holy One of Israel",
      "Holy One of Jacob",
      "Husband",
      "I Am",
      "Image of God",
      "Immanuel",
      "Jehovah",
      "Jesus",
      "Jesus Christ",
      "Judge of quick and dead",
      "Just One",
      "Keeper of the gate",
      "King",
      "King of heaven",
      "King of Israel",
      "Lamb",
      "Lamb of God",
      "Light",
      "Light of the world",
      "Living Bread",
      "Lord",
      "Lord both of the dead and living",
      "Lord God",
      "Lord God Almighty",
      "Lord God of Hosts",
      "Lord God Omnipotent",
      "Lord Jehovah",
      "Lord Jesus",
      "Lord Jesus Christ",
      "Lord of all",
      "Lord of Glory",
      "Lord of Hosts",
      "Lord of the Vineyard",
      "Lord Omnipotent",
      "Lord our Righteousness",
      "Maker",
      "Man",
      "Master",
      "Mediator",
      "Messenger of the covenant",
      "Messiah",
      "Messias",
      "Mighty God",
      "Mighty One of Israel",
      "Mighty One of Jacob",
      "Most High",
      "Most High God",
      "Only Begotten of the Father",
      "Only Begotten Son",
      "Potter",
      "Prince of Life",
      "Prince of Peace",
      "Prophet",
      "Rabbi",
      "Redeemer",
      "Redeemer of Israel",
      "Redeemer of the world",
      "Resurrection",
      "Rock",
      "Savior (Saviour)",
      "Savior (Saviour) of the World",
      "Savior Jesus Christ",
      "Shepherd",
      "Shiloh",
      "Son",
      "Son of God",
    "Son of Man",
    "Son of Righteousness",
    "Son of the Eternal Father",
    "Son of the Everlasting God",
"Son of the Highest",
"Son of the Living God",
"Son of the Most High God",
"Stem of Jesse",
"Stone",
"Supreme Being",
"Supreme Creator",
"Teacher",
"The Way, the Truth, and the Life",
"True and Living God",
"True Messiah",
"True Shepherd",
"True Vine",
"Well Beloved",
"Wonderful"]
const randomIndex = Math.floor(Math.random() * names.length);
  const randomName = names[randomIndex];
  return randomName;
}
for (let i=0; i <142; i++) {
console.log(generateName()); // Output a random name
}